alert("Mi primer programa");
console.log("Mi primer programa");
const a=25;
const b=30;
const c=a+b;
console.log("la suma es:",c);
let d=5;
let e=7;
let f=d+e;
console.log("la suma de d+e es:",f);
console.log("la resta es:",d-e);
console.log("la multiplicacion es:",d*e);
console.log("la division es:",d/e);
let valorA=parseInt(prompt("introduzca un numero"));
let valorB=prompt("introduzca un numero");
let res=valorA+parseInt(valorB);
alert(res);
valorA=parseFloat(prompt("introduzca un numero"));
valorB=prompt("introduzca un numero");
res=valorA+Number(valorB);
alert(res);
console.log(Boolean(0));
console.log(Boolean(1));
console.log(Boolean(""));
console.log(Boolean("hola"));